### ISSUE TITLE
Support occurrences higher than 5 to match RFC

### ISSUE THREAD

**Issue by PowerKiKi** [sabre-io/vobject#430]
This is an illogical but _potentially_ valid recurrence rule that lead me to discover a clear violation of the RFC. I have a VEVENT (coming from Google Calendar) with the following recurrence rule:

```
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=6SA
```

And this will incorrectly throw the following exception when trying to expand it:

```
Sabre\VObject\InvalidDataException: Invalid part in BYDAY clause: 6SA
#0 /my-project/vendor/sabre/vobject/lib/Recur/RRuleIterator.php(36): Sabre\VObject\Recur\RRuleIterator->parseRRule(Array)
#1 /my-project/vendor/sabre/vobject/lib/Recur/EventIterator.php(189): Sabre\VObject\Recur\RRuleIterator->__construct(Array, Object(DateTimeImmutable))
#2 /my-project/vendor/sabre/vobject/lib/Component/VCalendar.php(354): Sabre\VObject\Recur\EventIterator->__construct(Array, Object(DateTimeZone))
#3 /my-project/module/Application/src/Service/Importer.php(180): Sabre\VObject\Component\VCalendar->expand(Object(DateTimeImmutable), Object(DateTimeImmutable))
```

It is clear that this lib consider occurences invalid if they are not in the range of 1-5:

https://github.com/sabre-io/vobject/blob/18e76a319358ae532d2f223d9e846c68ee31d0e3/lib/Recur/RRuleIterator.php#L727-L735

I guess we could argue that the 6th Saturday of a month will never exists, and thus it is correct to throw an exception. But I believe it should be accepted and returns nothing when expanded. And this is because the RFC at the [end of page 41](https://tools.ietf.org/html/rfc5545#page-41) says nothing about any kind of restriction about the integer used to express occurences:

> Each BYDAY value can also be preceded by a positive (+n) or
> negative (-n) integer.  If present, this indicates the nth
> occurrence of a specific day within the MONTHLY or YEARLY "RRULE".

In fact it actually has an exemple showcasing a valid usage of occurrences with two digits [on page 128](https://tools.ietf.org/html/rfc5545#page-128):

>       Every 20th Monday of the year, forever:
> 
>        DTSTART;TZID=America/New_York:19970519T090000
>        RRULE:FREQ=YEARLY;BYDAY=20MO
> 
>        ==> (1997 9:00 AM EDT) May 19
>            (1998 9:00 AM EDT) May 18
>            (1999 9:00 AM EDT) May 17
>            ...

The following code is a test case to be added to `\Sabre\VObject\Recur\RRuleIteratorTest` that demonstrate that this lib is not implementing the RFC correctly.

```php
    public function testEvery20thMondayOfTheYear()
    {
        $this->parse(
            'FREQ=YEARLY;BYDAY=20MO',
            '1997-05-19 09:00:00',
            [
                '1997-05-19 09:00:00',
                '1998-05-18 09:00:00',
                '1999-05-17 09:00:00',
            ]
        );
    }
```

There are in fact **three problems**:

- occurrences must not be limited to 1-5
- BYDAY rule is totally ignored by `\Sabre\VObject\Recur\RRuleIterator::nextYearly()`
- even if BYMONTH is specified, `nextYearly()` will treat BYDAY as if occurrence never exists

The last problem is obvious when comparing the correct `getMonthlyOccurrences()`:

https://github.com/sabre-io/vobject/blob/18e76a319358ae532d2f223d9e846c68ee31d0e3/lib/Recur/RRuleIterator.php#L815

with the incorrect `nextYearly()`:

https://github.com/sabre-io/vobject/blob/18e76a319358ae532d2f223d9e846c68ee31d0e3/lib/Recur/RRuleIterator.php#L510

https://github.com/sabre-io/vobject/blob/18e76a319358ae532d2f223d9e846c68ee31d0e3/lib/Recur/RRuleIterator.php#L548

So I am willing to help with that and create a PR to solve all three issues, but only if you agree that high occurrences should be silently accepted and expanded to nothing. What do you think ?

**Comment by evert** [comment]
You're totally right that this is missing. It's a documented unimplemented feature though. There's actually a LOT of things missing from the `RRULE` iterator. See here:

https://github.com/sabre-io/vobject/blob/master/lib/Recur/EventIterator.php#L28

When I first wrote this, I just implemented the things I saw the wild and my intent was to implement more as people requested it.

If you want this feature and can contribute it + tests, it would definitely be appreciated.

**Comment by PowerKiKi** [comment]
Time has passed and I never got to implement a PR for this. If anybody else is willing to help with that, feel free to do it, because it is unlikely that I will do it myself in the foreseeable future.
